"""Canvas renderer timing adapter for the generic profiling model."""
from __future__ import annotations

from lks_utils.profiling.call_node import CallNode
from lks_utils.profiling.device import Device
from lks_utils.profiling.frame_sample import FrameSample

# Overlay names that originate from the GPU render path start with "GPU".
# These are generated by canvas2d_gl_widget.py and should be attributed
# to the GPU device in the profiling hierarchy.
_GPU_NAME_PREFIX = "GPU"

# Stage names matching this prefix are GPU↔CPU handoff timings (A6).
# Emitted by GpuHandoffTimer via ``gpu_handoff.<reason>`` convention.
_HANDOFF_STAGE_PREFIX = "gpu_handoff."


def _device_for_overlay_name(name: str) -> Device:
    """Return the appropriate :class:`Device` for a named overlay timing."""
    return Device.GPU if name.startswith(_GPU_NAME_PREFIX) else Device.CPU


def device_for_stage_name(name: str) -> Device:
    """Return the :class:`Device` for a profiler stage name.

    Extends the overlay-name heuristic to also classify ``gpu_handoff.*``
    stages (emitted by :class:`~lks_utils.gpu.gpu_handoff_timer.GpuHandoffTimer`)
    as :attr:`~lks_utils.profiling.device.Device.HANDOFF`.
    """
    if name.startswith(_HANDOFF_STAGE_PREFIX):
        return Device.HANDOFF
    if name.startswith(_GPU_NAME_PREFIX):
        return Device.GPU
    return Device.CPU


class CanvasFrameTimingsAdapter:
    """Map ``FrameTimings`` records into generic ``FrameSample`` trees."""

    @staticmethod
    def adapt(frame, *, frame_index: int = 0) -> FrameSample:  # noqa: ANN001
        # ── Classify overlay timings by z_order ────────────────────────────
        # z=-1000: combined CPU wall time for the entire bg GPU pass.
        #          canvas2d_gl_widget.py also adds this value to background_ms,
        #          so it must become a *child* of the background node — not a
        #          sibling — to avoid double-counting.
        # z=-1001: individual GPU overlay CPU submit times (sub-parts of -1000)
        # z=-1002: individual GPU overlay GPU-side elapsed times.
        #          These are ASYNC timer query results — they overlap the CPU
        #          timeline and MUST NOT be additive call-tree children.
        # z=+1000/+1001/+1002: same pattern for the foreground GPU pass.
        # All other z values: CPU-side overlays (CoordHud, Qt GL flush, …)
        gpu_bg_combined = None
        gpu_bg_submit: list = []
        gpu_bg_elapsed: list = []
        gpu_fg_combined = None
        gpu_fg_submit: list = []
        gpu_fg_elapsed: list = []
        cpu_overlays: list = []
        for ov in frame.overlay_timings:
            z = int(ov.z_order)
            if z == -1000:
                gpu_bg_combined = ov
            elif z == -1001:
                gpu_bg_submit.append(ov)
            elif z == -1002:
                gpu_bg_elapsed.append(ov)
            elif z == 1000:
                gpu_fg_combined = ov
            elif z == 1001:
                gpu_fg_submit.append(ov)
            elif z == 1002:
                gpu_fg_elapsed.append(ov)
            else:
                cpu_overlays.append(ov)

        def _gpu_pass_node(combined, submits: list, elapsed: list):  # noqa: ANN001
            """Build a CallNode subtree for one GPU pass (bg or fg).

            GPU elapsed timings are stored as metadata only — they are async
            GPU timer query results that must not inflate CPU-wall totals.
            """
            if combined is None:
                return None
            elapsed_meta = {ov.name: float(ov.duration_ms) for ov in elapsed}
            submit_nodes: tuple[CallNode, ...] = tuple(
                CallNode(
                    name=ov.name,
                    category="overlay",
                    device=Device.GPU,
                    self_ms=max(0.0, float(ov.duration_ms)),
                    metadata={"z_order": int(ov.z_order)},
                )
                for ov in submits
            )
            combined_ms = max(0.0, float(combined.duration_ms))
            submit_sum = sum(n.total_ms_value for n in submit_nodes)
            # Use the larger of the two to tolerate measurement noise where
            # individual submit times marginally exceed the combined timer.
            node_total_ms = max(combined_ms, submit_sum)
            node_self_ms = max(0.0, combined_ms - submit_sum)
            return CallNode(
                name=combined.name,
                category="overlay",
                device=Device.GPU,
                self_ms=node_self_ms,
                total_ms=node_total_ms,
                children=submit_nodes,
                metadata={"z_order": int(combined.z_order), **elapsed_meta},
            )

        gpu_bg_node = _gpu_pass_node(
            gpu_bg_combined, gpu_bg_submit, gpu_bg_elapsed)
        gpu_fg_node = _gpu_pass_node(
            gpu_fg_combined, gpu_fg_submit, gpu_fg_elapsed)

        # ── Background node ─────────────────────────────────────────────────
        # background_ms already includes gpu_bg_ms (injected by
        # canvas2d_gl_widget.py).  Make the GPU bg subtree a child so the
        # tree reflects actual ownership without double-counting.
        if gpu_bg_node is not None:
            bg_ms = max(0.0, float(frame.background_ms))
            bg_total = max(bg_ms, gpu_bg_node.total_ms_value)
            bg_self = max(0.0, bg_ms - gpu_bg_node.total_ms_value)
            background_node = CallNode(
                name="background",
                category="background",
                device=Device.CPU,
                self_ms=bg_self,
                total_ms=bg_total,
                children=(gpu_bg_node,),
            )
        else:
            background_node = CallNode(
                name="background",
                category="background",
                device=Device.CPU,
                self_ms=max(0.0, float(frame.background_ms)),
            )

        # ── CPU overlays node (+ optional fg GPU pass) ──────────────────────
        cpu_ov_nodes: list[CallNode] = [
            CallNode(
                name=ov.name,
                category="overlay",
                device=_device_for_overlay_name(ov.name),
                self_ms=max(0.0, float(ov.duration_ms)),
                metadata={"z_order": int(ov.z_order)},
            )
            for ov in cpu_overlays
        ]
        if gpu_fg_node is not None:
            cpu_ov_nodes.append(gpu_fg_node)
        overlays_node = CallNode(
            name="overlays",
            category="overlay_group",
            device=Device.UNKNOWN,
            self_ms=0.0,
            children=tuple(cpu_ov_nodes),
        )

        items_node = CallNode(
            name="items",
            category="items",
            device=Device.CPU,
            self_ms=max(0.0, float(frame.items_ms)),
        )

        qpainter_init_ms = max(0.0, float(
            getattr(frame, "qpainter_init_ms", 0.0)))
        qpainter_flush_ms = max(0.0, float(
            getattr(frame, "qpainter_flush_ms", 0.0)))

        # ── Root frame node ─────────────────────────────────────────────────
        children_list: list[CallNode] = [
            background_node, items_node, overlays_node]
        if qpainter_init_ms > 0.0:
            children_list.append(CallNode(
                name="QPainter init",
                category="qpainter",
                device=Device.CPU,
                self_ms=qpainter_init_ms,
                metadata={
                    "detail": "QPainter(widget) constructor — GL state save/pipeline sync"},
            ))
        if qpainter_flush_ms > 0.0:
            children_list.append(CallNode(
                name="QPainter flush",
                category="qpainter",
                device=Device.CPU,
                self_ms=qpainter_flush_ms,
                metadata={
                    "detail": "painter.end() — Qt GL command flush to driver"},
            ))
        children: tuple[CallNode, ...] = tuple(children_list)
        accounted_ms = sum(child.total_ms_value for child in children)
        frame_total = max(0.0, float(frame.total_ms))
        # residual covers untracked render overhead; clamped to 0 when GPU
        # measurement noise makes accounted_ms slightly exceed frame_total.
        residual_ms = max(0.0, frame_total - accounted_ms)
        # total_ms must be >= self_ms + sum(children) per CallNode contract;
        # use max to tolerate GPU measurement noise in either direction.
        root_total_ms = max(frame_total, accounted_ms + residual_ms)
        root = CallNode(
            name="frame",
            category="frame",
            device=Device.UNKNOWN,
            self_ms=residual_ms,
            total_ms=root_total_ms,
            children=children,
            metadata={
                "frame_timestamp": float(frame.frame_timestamp),
                "frame_start_timestamp": float(getattr(frame, "frame_start_timestamp", 0.0) or 0.0),
                "frame_end_timestamp": float(getattr(frame, "frame_end_timestamp", 0.0) or 0.0),
            },
        )
        return FrameSample(
            frame_index=max(0, int(frame_index)),
            wall_ms=frame_total,
            call_tree=root,
            metadata={"source": "canvas_frame_timings"},
        )


__all__ = ["CanvasFrameTimingsAdapter", "device_for_stage_name"]
